Graphs go full width
astoria-tech/50-a-foil-status pull request #38
Opened 2021-02-22 18:59 UTC by bronzehedwick

Change layout so the graphs blow out to full width when the screen is
large enough to support this, while keeping the text content and a
comfortable, narrow, and centered width.

Hoping this will showcase graphs nicely while allowing text to stay
readable.

I had this idea while looking into form styling, which I think could benefit from some version of this approach as well, but wanted to submit the idea to the team first before plowing ahead.

I put everyone on the PR as a reviewer for visibility, but I think it can be merged after 2 approvals (that's a general philosophy of mine, feel free to disagree).

## Screenshots

### Large screens
![Screen Shot 2021-02-22 at 13 41 48-fullpage](https://user-images.githubusercontent.com/637174/108756019-fdef1800-7515-11eb-88bd-11f099b8a10f.png)

### Small screens
![Screen Shot 2021-02-22 at 13 50 18-fullpage](https://user-images.githubusercontent.com/637174/108756033-00517200-7516-11eb-850a-80d78e8a279a.png)

2021-02-23 01:29 UTC, ashryanbeats approved these changes

2021-02-23 01:30 UTC, ashryanbeats commented
LGMT☆

2021-02-23 14:22 UTC, aniagaska requested changes
I think that the bar graph, especially the cost visualization works very nicely full width. The status tree chart could use some padding on it to make it easy to look at it all and get a general sense of the information

2021-02-24 01:55 UTC, bronzehedwick commented
@aniagaska I updated responding to your feedback. Please see updated screenshot for treemap below.
<img width="1152" alt="Screen Shot 2021-02-23 at 8 51 13 PM" src="https://user-images.githubusercontent.com/637174/108933574-61ae3980-7619-11eb-9cdf-36b0a9e6a41c.png">

2021-02-25 03:30 UTC, aniagaska approved these changes
Beautiful!

2021-02-25 13:38 UTC, merged