Implemented menu
astoria-tech/50-a-foil-status pull request #43
Opened 2021-02-24 20:03 UTC by olesia-ag

**mobile (not sure if the menu should cover the header?)**:
<img width="337" alt="Screen Shot 2021-02-24 at 2 55 34 PM" src="https://user-images.githubusercontent.com/47761058/109058364-e7c98f00-76b0-11eb-8d3d-18d3047365bf.png">
**desktop**:
<img width="1267" alt="Screen Shot 2021-02-24 at 2 37 54 PM" src="https://user-images.githubusercontent.com/47761058/109058448-03349a00-76b1-11eb-8819-fa569de0599a.png">
<img width="1278" alt="Screen Shot 2021-02-24 at 2 37 42 PM" src="https://user-images.githubusercontent.com/47761058/109058461-06c82100-76b1-11eb-8b59-e9c9ed9b9400.png">

2021-02-24 21:59 UTC, aniagaska reviewed
It can replace the header! It would be good if it didn't overlap on the rest of the content of the site -- could the subheading and the rest of the content of the page get pushed down by it?

2021-02-24 23:35 UTC, olesia-ag commented
@aniagaska I can just it the exact same height as the header on mobile, and make a top margin for the subheading ("Visualizing the process..") bigger so that the menu doesn't cover it on the desktop view - if I push it only when the menu is opened (if I understood what you meant), I think it might look like the text on the page 'jumps' up and down

2021-02-25 13:54 UTC, aniagaska commented
@olesia-ag that makes sense to me! I wouldn't want the transition to be jumpy. Thanks Olesia!

2021-02-25 15:38 UTC, bronzehedwick requested changes
This is great, thanks Olesia! Had just one minor formatting comment and then I think we'll be good to merge in.

2021-02-25 15:38 UTC, bronzehedwick commented on browser/src/components/Toolbar/NavigationItems/NavigationItems.js
> +		<div  className="navigation_items">
Can we fix the indentation levels here?

2021-02-27 20:12 UTC, bronzehedwick approved these changes

2021-02-27 20:12 UTC, merged