Add top-level start/stop script
astoria-tech/50-a-foil-status pull request #44
Opened 2021-02-25 02:36 UTC by bronzehedwick

This PR aggregates both the server and browser default startup commands
into one single command. It also sends the tasks into the background,
saving the output to log files. The process IDs are saved, so they can
be stopped on demand.

This depends on #40 being complete before it will work, since the
interactive element of having to say "Yes" to a new port on the browser
stops that from starting.

Fixes #41

2021-02-27 22:22 UTC, ashryanbeats commented
Having a look now :)

2021-02-27 23:05 UTC, ashryanbeats reviewed
For me, `npm start` would start the server fine, but the react app never seemed to start for me (note that I had already swapped the ports locally via #46). 

`browser.log` would log through CRA's "starting the development server..." message, then nothing: the browser wouldn't load the app and it seemed like maybe the Node.js process would die, but I wasn't sure.

2021-02-28 21:49 UTC, bronzehedwick commented
@ashryanbeats I updated this PR with a new approach (updated commit message/comment above to reflect) which solves the issue on my end. Hopefully makes the project a bit easier to work with as well.

2021-03-02 02:52 UTC, ashryanbeats commented
Having a look

2021-03-02 03:06 UTC, ashryanbeats requested changes
The server is spinning up just fine! And the stop script works perfectly.

I'm getting this compile error on the front end. Just a guess, but is it possible that you have something globally installed locally?

```
Failed to compile

./src/App.js
Error: [BABEL] ~/Dev/astoria-tech/muckrock/6/browser/src/App.js: Cannot find module '@babel/helper-regex'
```

I did an npm install in the following locations before running:

1. the root directory
2. /server
3. /browser

2021-03-14 21:00 UTC, bronzehedwick commented
Hey @ashryanbeats, finally had a moment to re-test this, and was unable to replicate the issue. Here's my steps:

1. Clone a fresh copy of the repo
2. `npm install` in root
3. `npm start` in root

2021-03-31 00:17 UTC, bronzehedwick commented
Closing this PR to review after Alex's data changes.

2021-03-31 00:17 UTC, closed without merging